### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by khadijahMu**

### CODE REVIEW

**Comment by Devsalmasaeed** [comment]
Hi Khadija you submitted empty file check and resubmit your pull request link

**Comment by khadijahMu** [comment]
i've updated and resubmitted the pull request link

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @khadijahMu 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- You didn't put the images paths correctly in your html, that's why the images in your website are not showing, please do rectify it
- Your commits shouldn't be less than a minimun of 3-5 commits



### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Comment by khadijahMu** [comment]
Thank you, I will do that.

**Pull request merged**
